version: '3'

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.1.0/24

services:
  company-mentions:
    image: annieka/company-mentions
    labels:
      - "com.centurylinklabs.watchtower.scope=myscope"
    environment:
      TELEGRAM_BOT_TOKEN: "${TELEGRAM_BOT_TOKEN}"
    env_file:
      - .env

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
    labels:
      - "com.centurylinklabs.watchtower.scope=myscope"


